modLoader="lowcodefml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
  modId="tectonic"
  version="1.1.4"
  displayName="Tectonic"
  logoFile="pack.png"
  authors="Apollo404, Catalyst"
  description='''
  25+ new biomes, new terrain features, and more!
  '''

  [[dependencies.tectonic]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.tectonic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"